package com.spark.bitrade.messager.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table member_mail_content
 */
public class MemberMailContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail_content.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   站内信内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail_content.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail_content.id
     *
     * @return the value of member_mail_content.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail_content.id
     *
     * @param id the value for member_mail_content.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail_content.content
     *
     * @return the value of member_mail_content.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail_content.content
     *
     * @param content the value for member_mail_content.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}